### ISSUE TITLE
Should we include shared repos directly in manifestly?

### ISSUE THREAD

**Issue by philschatz** [openstax/manifestly#4]
Currently, shared repos like `react-components` and `concept-coach` (not deployable on their own) are used by `tutor-js` and `webview` (deployable).

But whenever we make a change to them, we have to make 1-line PR's to change the `package.json` (a `npm` thing) to all the other repos to keep them in sync.

If manifestly had their commits directly:

1. developers choose which version of these repos are used for an entire environment, not just `tutor-js` or `webview`
2. QA could see the list of changes made better by diffing the commits instead of diffing the commits that are in a commit in webview/tutor-js

I can take a look at how to get `npm` to install these packages (maybe `npm install -g`?) so they:

1.  would not _need_ to be included in `package.json`
2. could override the version inside `package.json`

/cc @nathanstitt @jpslav @kevinburleigh75 @dantemss. Anyone else that might be interested? maybe Chris?

**Comment by jpslav** [comment]
Hmmm... maybe.  I kind of see this as a parallel to the Rails engines we use across our different sites, e.g. openstax_api, accounts-rails, openstax_utilities, fine_print, etc, and I would not want to include these in the manifest in this way.  These engines/gems are referenced from the Rails app's `Gemfile` and `Gemfile.lock`, and it is true that when we change the lib we have to change the apps that use them.  OTOH, our libs are probably not changing as often as yours are now.  So I'm up in the air on this :-)

**Comment by Dantemss** [comment]
Depends how much control you want over the versioning of the shared package and how afraid you are of changes to one app causing regressions in the other app...

**Comment by nathanstitt** [comment]
It seems to me that having a reference to an explicit version of the shared FE/BE repo in `package.json` or `Gemfile.lock` is a good thing both from development and deployment perspectives.  

The alternative would require us to test a change in the shared repo on all it's consumers before merge.  One thing to make that simpler would be to use semantic versioning, but even that's not going to be 100% reliable.

If we wanted to, we could work around the (admittedly small) pain of the separate PR by making an administrative rule that whoever merges the shared repo PR should update the SHA reference on master of the affected repo.  The commit message of the edit should reference the original PR and contain a message indicating what changes it brings.

**Comment by philschatz** [comment]
I'm not sure how we would "test a change in the shared repo on all it's consumers before merge" unless we:

1. remembered _all_ the consumers
2. remembered to create 1-line PR's for all of them before testing (with detailed descriptions/screenshots of all the changes)
3. deployed all the consumers with those PR's

Seems like a lot of (error-prone) work to test an update to a shared repo. But maybe I'm over-estimating the amount of work? Also, I think it will only get more annoying as we create more shared repos across the openstax org.

The alternative would be to:

1. install the repo globally for deployments, or use `npm link` if doing local testing without adding to package.json
2. specifically adding an entry to `package.json` if we _really really_ need a different version than what is installed globally (like not ready to release)

**Comment by Dantemss** [comment]
Does the FE deployment support having different versions of the same package? The whole point of the `Gemfile.lock` is that you don't HAVE to update all apps at once (you might want to, if it's some serious bug that affects all apps, though)

**Comment by nathanstitt** [comment]
@Dantemss, yeah the `package.json` is part of NPM (Node Package Manager).  It has pretty much the same features as `Gemfile`, but installs all the packages into a `node_modules` subdirectory instead of `GEM_HOME`

**Comment by philschatz** [comment]
@Dantemss: correct, it provides having different versions of the same package. I think my suggestion stems from 3 things:

1. What should the _default_ be within an organization? multiple versions of our own libs running on production, or just 1?
1. "deployable" repos get to be installed/tested globally which makes it easy to reason about what is on production, why not (at least some) libs?
1. how can we _easily_ see what is being deployed (for hotfixes/QA)

RE 1: When a package is used by an unknown number of people in an unknown number of ways I think `package.json` / `Gemfile` makes a ton of sense, but _within_ an organization I think we would prefer to have a single version of _our own code_ running on all the services.

RE 2: Similar to how each environment has a single copy of `tutor-server`, `exercises`, `webview`, `archive`, etc. I guess why treat non-deployable repos differently than deployable ones? If we want to try and keep 1 version of code running in production then I think it should be easy to deploy our code (see my previous comment)

RE 3: mentioned in my comment above :smile:

**Comment by jpslav** [comment]
RE PS's 1: While we might prefer to have a single version of code running, for compatibility reasons we may not (e.g. Accounts is on older version of Ruby so maybe can't use later version of some of our libs, but that's ok).

RE PS's 2: Seeming scarier to me to be duplicating / deviating from standard library referencing in package.json / Gemfile.lock.

RE PS's 3: The shared libraries are in the manifest via the consuming app's SHAs (admittedly, not "directly", but they are accounted for there)

Two other thoughts:

1. Also for development purposes, aren't you going to want to have the updated version of the shared libs in package.json, etc? (don't FEs do development without a concept of "deploying").  
2. If we really want 1 version of `react-components`, can this library be deployed and then have tutor and webview link to that deployed JS in the browser? (wondering if we're trying to solve the wrong problem)

**Comment by nathanstitt** [comment]
Was chatting with @philschatz about how version #'s work with bundler and how a project could select the manifestly version.  Since the Gemfile is "just ruby" I think we could use manifestly's as an API inside it?  For instance we could have lines such as:

```ruby
# URI replacement
gem 'addressable'

# Utilities for OpenStax websites
gem 'openstax_utilities',  Manifestly.version_for('openstax_utilities')

# Cron job scheduling
gem 'whenever'
```

**Comment by Dantemss** [comment]
Hm potentially. Though for example Accounts uses old gems and we can't really change that until we upgrade it to Rails 4.

**Comment by philschatz** [comment]
The discussion was around having a global version of our libs by default and still having a way to specify a local version if needed. If it wasn't possible or easy, I agree my suggestion would be dumb because we'd "paint ourselves in a corner".

But there _is_ a simple way to do it with `package.json` and I was wondering if there was a way to do it in `Gemfile` (and @nathanstitt pointed out that `package.json` was heavily inspired by `Gemfile`)

**Comment by Dantemss** [comment]
You'd have to require manifestly somehow before the gemfile (I guess this means Manifestly must be installed globally?) Then you could even extend the gemfile functionality and add stuff like `manifest 'openstax_utilities'` or something. Should work, I think.

**Comment by philschatz** [comment]
Any thoughts/opinions/feedback beforehand since folks will be discussing this tomorrow?

**Comment by pandafulmanda** [comment]
@philschatz sorry, I will read up on this this evening and post my thoughts

**Comment by jpslav** [comment]
My vote after all of the above is not having these libs in manifestly.

**Comment by philschatz** [comment]
Thanks for the feedback! I think the main bottleneck (`concept-coach` repo) is being looked at by @pandafulmanda; looking at either moving it into the `tutor-js` repo and having an additional `.js` file in `https://tutor/assets/` or by building it in `cnx-deploy` (probably less-likely).

Closing this and we'll see what happens!
